server:
  port: ${PORT:52890}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      roles: USER
      show-details: always
    env.show-values: ALWAYS

logging.level:
  com.vmware.sfdc.demo=: DEBUG
  # org.springframework.http.server.reactive: INFO
  # org.springframework.web.reactive: INFO
  # reactor.ipc.netty: INFO
  # reactor.netty: INFO
# springdoc:
#   swagger-ui.path: "/swagger-ui.html"
#   api-docs.path: "/api-docs"

sfdc:
  authserviceURL: "http://localhost:8080/authservice/api"

---
spring:
  config:
    activate:
      on-profile: k8s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-83469100.okta.com/oauth2/aus7m6k7v5EdD4eoQ5d7/v1/keys
